// AUTO-GENERATED by scripts/generate-i18n-registry.mjs — do not edit manually.
// Statically imports every translation namespace so the i18n engine works in any
// bundler/runtime (webpack, Turbopack, Node) without dynamic require().

import ar_admin from "./ar/admin.json";
import ar_billing from "./ar/billing.json";
import ar_chat from "./ar/chat.json";
import ar_common from "./ar/common.json";
import ar_creator from "./ar/creator.json";
import ar_dating from "./ar/dating.json";
import ar_errors from "./ar/errors.json";
import ar_feed from "./ar/feed.json";
import ar_help from "./ar/help.json";
import ar_moderation from "./ar/moderation.json";
import ar_navigation from "./ar/navigation.json";
import ar_notifications from "./ar/notifications.json";
import ar_onboarding from "./ar/onboarding.json";
import ar_premium from "./ar/premium.json";
import ar_profile from "./ar/profile.json";
import ar_search from "./ar/search.json";
import ar_settings from "./ar/settings.json";
import ar_stories from "./ar/stories.json";
import ar_support from "./ar/support.json";
import ar_time from "./ar/time.json";
import bn_admin from "./bn/admin.json";
import bn_billing from "./bn/billing.json";
import bn_chat from "./bn/chat.json";
import bn_common from "./bn/common.json";
import bn_creator from "./bn/creator.json";
import bn_dating from "./bn/dating.json";
import bn_errors from "./bn/errors.json";
import bn_feed from "./bn/feed.json";
import bn_help from "./bn/help.json";
import bn_moderation from "./bn/moderation.json";
import bn_navigation from "./bn/navigation.json";
import bn_notifications from "./bn/notifications.json";
import bn_onboarding from "./bn/onboarding.json";
import bn_premium from "./bn/premium.json";
import bn_profile from "./bn/profile.json";
import bn_search from "./bn/search.json";
import bn_settings from "./bn/settings.json";
import bn_stories from "./bn/stories.json";
import bn_support from "./bn/support.json";
import bn_time from "./bn/time.json";
import en_admin from "./en/admin.json";
import en_billing from "./en/billing.json";
import en_chat from "./en/chat.json";
import en_common from "./en/common.json";
import en_creator from "./en/creator.json";
import en_dating from "./en/dating.json";
import en_errors from "./en/errors.json";
import en_feed from "./en/feed.json";
import en_help from "./en/help.json";
import en_moderation from "./en/moderation.json";
import en_navigation from "./en/navigation.json";
import en_notifications from "./en/notifications.json";
import en_onboarding from "./en/onboarding.json";
import en_premium from "./en/premium.json";
import en_profile from "./en/profile.json";
import en_search from "./en/search.json";
import en_settings from "./en/settings.json";
import en_stories from "./en/stories.json";
import en_support from "./en/support.json";
import en_time from "./en/time.json";
import es_admin from "./es/admin.json";
import es_billing from "./es/billing.json";
import es_chat from "./es/chat.json";
import es_common from "./es/common.json";
import es_creator from "./es/creator.json";
import es_dating from "./es/dating.json";
import es_errors from "./es/errors.json";
import es_feed from "./es/feed.json";
import es_help from "./es/help.json";
import es_moderation from "./es/moderation.json";
import es_navigation from "./es/navigation.json";
import es_notifications from "./es/notifications.json";
import es_onboarding from "./es/onboarding.json";
import es_premium from "./es/premium.json";
import es_profile from "./es/profile.json";
import es_search from "./es/search.json";
import es_settings from "./es/settings.json";
import es_stories from "./es/stories.json";
import es_support from "./es/support.json";
import es_time from "./es/time.json";
import fr_admin from "./fr/admin.json";
import fr_billing from "./fr/billing.json";
import fr_chat from "./fr/chat.json";
import fr_common from "./fr/common.json";
import fr_creator from "./fr/creator.json";
import fr_dating from "./fr/dating.json";
import fr_errors from "./fr/errors.json";
import fr_feed from "./fr/feed.json";
import fr_help from "./fr/help.json";
import fr_moderation from "./fr/moderation.json";
import fr_navigation from "./fr/navigation.json";
import fr_notifications from "./fr/notifications.json";
import fr_onboarding from "./fr/onboarding.json";
import fr_premium from "./fr/premium.json";
import fr_profile from "./fr/profile.json";
import fr_search from "./fr/search.json";
import fr_settings from "./fr/settings.json";
import fr_stories from "./fr/stories.json";
import fr_support from "./fr/support.json";
import fr_time from "./fr/time.json";
import hi_admin from "./hi/admin.json";
import hi_billing from "./hi/billing.json";
import hi_chat from "./hi/chat.json";
import hi_common from "./hi/common.json";
import hi_creator from "./hi/creator.json";
import hi_dating from "./hi/dating.json";
import hi_errors from "./hi/errors.json";
import hi_feed from "./hi/feed.json";
import hi_help from "./hi/help.json";
import hi_moderation from "./hi/moderation.json";
import hi_navigation from "./hi/navigation.json";
import hi_notifications from "./hi/notifications.json";
import hi_onboarding from "./hi/onboarding.json";
import hi_premium from "./hi/premium.json";
import hi_profile from "./hi/profile.json";
import hi_search from "./hi/search.json";
import hi_settings from "./hi/settings.json";
import hi_stories from "./hi/stories.json";
import hi_support from "./hi/support.json";
import hi_time from "./hi/time.json";
import id_admin from "./id/admin.json";
import id_billing from "./id/billing.json";
import id_chat from "./id/chat.json";
import id_common from "./id/common.json";
import id_creator from "./id/creator.json";
import id_dating from "./id/dating.json";
import id_errors from "./id/errors.json";
import id_feed from "./id/feed.json";
import id_help from "./id/help.json";
import id_moderation from "./id/moderation.json";
import id_navigation from "./id/navigation.json";
import id_notifications from "./id/notifications.json";
import id_onboarding from "./id/onboarding.json";
import id_premium from "./id/premium.json";
import id_profile from "./id/profile.json";
import id_search from "./id/search.json";
import id_settings from "./id/settings.json";
import id_stories from "./id/stories.json";
import id_support from "./id/support.json";
import id_time from "./id/time.json";
import pt_admin from "./pt/admin.json";
import pt_billing from "./pt/billing.json";
import pt_chat from "./pt/chat.json";
import pt_common from "./pt/common.json";
import pt_creator from "./pt/creator.json";
import pt_dating from "./pt/dating.json";
import pt_errors from "./pt/errors.json";
import pt_feed from "./pt/feed.json";
import pt_help from "./pt/help.json";
import pt_moderation from "./pt/moderation.json";
import pt_navigation from "./pt/navigation.json";
import pt_notifications from "./pt/notifications.json";
import pt_onboarding from "./pt/onboarding.json";
import pt_premium from "./pt/premium.json";
import pt_profile from "./pt/profile.json";
import pt_search from "./pt/search.json";
import pt_settings from "./pt/settings.json";
import pt_stories from "./pt/stories.json";
import pt_support from "./pt/support.json";
import pt_time from "./pt/time.json";
import tr_admin from "./tr/admin.json";
import tr_billing from "./tr/billing.json";
import tr_chat from "./tr/chat.json";
import tr_common from "./tr/common.json";
import tr_creator from "./tr/creator.json";
import tr_dating from "./tr/dating.json";
import tr_errors from "./tr/errors.json";
import tr_feed from "./tr/feed.json";
import tr_help from "./tr/help.json";
import tr_moderation from "./tr/moderation.json";
import tr_navigation from "./tr/navigation.json";
import tr_notifications from "./tr/notifications.json";
import tr_onboarding from "./tr/onboarding.json";
import tr_premium from "./tr/premium.json";
import tr_profile from "./tr/profile.json";
import tr_search from "./tr/search.json";
import tr_settings from "./tr/settings.json";
import tr_stories from "./tr/stories.json";
import tr_support from "./tr/support.json";
import tr_time from "./tr/time.json";

const resources: Record<string, Record<string, unknown>> = {
  "ar": {
    "admin": ar_admin,
    "billing": ar_billing,
    "chat": ar_chat,
    "common": ar_common,
    "creator": ar_creator,
    "dating": ar_dating,
    "errors": ar_errors,
    "feed": ar_feed,
    "help": ar_help,
    "moderation": ar_moderation,
    "navigation": ar_navigation,
    "notifications": ar_notifications,
    "onboarding": ar_onboarding,
    "premium": ar_premium,
    "profile": ar_profile,
    "search": ar_search,
    "settings": ar_settings,
    "stories": ar_stories,
    "support": ar_support,
    "time": ar_time,
  },
  "bn": {
    "admin": bn_admin,
    "billing": bn_billing,
    "chat": bn_chat,
    "common": bn_common,
    "creator": bn_creator,
    "dating": bn_dating,
    "errors": bn_errors,
    "feed": bn_feed,
    "help": bn_help,
    "moderation": bn_moderation,
    "navigation": bn_navigation,
    "notifications": bn_notifications,
    "onboarding": bn_onboarding,
    "premium": bn_premium,
    "profile": bn_profile,
    "search": bn_search,
    "settings": bn_settings,
    "stories": bn_stories,
    "support": bn_support,
    "time": bn_time,
  },
  "en": {
    "admin": en_admin,
    "billing": en_billing,
    "chat": en_chat,
    "common": en_common,
    "creator": en_creator,
    "dating": en_dating,
    "errors": en_errors,
    "feed": en_feed,
    "help": en_help,
    "moderation": en_moderation,
    "navigation": en_navigation,
    "notifications": en_notifications,
    "onboarding": en_onboarding,
    "premium": en_premium,
    "profile": en_profile,
    "search": en_search,
    "settings": en_settings,
    "stories": en_stories,
    "support": en_support,
    "time": en_time,
  },
  "es": {
    "admin": es_admin,
    "billing": es_billing,
    "chat": es_chat,
    "common": es_common,
    "creator": es_creator,
    "dating": es_dating,
    "errors": es_errors,
    "feed": es_feed,
    "help": es_help,
    "moderation": es_moderation,
    "navigation": es_navigation,
    "notifications": es_notifications,
    "onboarding": es_onboarding,
    "premium": es_premium,
    "profile": es_profile,
    "search": es_search,
    "settings": es_settings,
    "stories": es_stories,
    "support": es_support,
    "time": es_time,
  },
  "fr": {
    "admin": fr_admin,
    "billing": fr_billing,
    "chat": fr_chat,
    "common": fr_common,
    "creator": fr_creator,
    "dating": fr_dating,
    "errors": fr_errors,
    "feed": fr_feed,
    "help": fr_help,
    "moderation": fr_moderation,
    "navigation": fr_navigation,
    "notifications": fr_notifications,
    "onboarding": fr_onboarding,
    "premium": fr_premium,
    "profile": fr_profile,
    "search": fr_search,
    "settings": fr_settings,
    "stories": fr_stories,
    "support": fr_support,
    "time": fr_time,
  },
  "hi": {
    "admin": hi_admin,
    "billing": hi_billing,
    "chat": hi_chat,
    "common": hi_common,
    "creator": hi_creator,
    "dating": hi_dating,
    "errors": hi_errors,
    "feed": hi_feed,
    "help": hi_help,
    "moderation": hi_moderation,
    "navigation": hi_navigation,
    "notifications": hi_notifications,
    "onboarding": hi_onboarding,
    "premium": hi_premium,
    "profile": hi_profile,
    "search": hi_search,
    "settings": hi_settings,
    "stories": hi_stories,
    "support": hi_support,
    "time": hi_time,
  },
  "id": {
    "admin": id_admin,
    "billing": id_billing,
    "chat": id_chat,
    "common": id_common,
    "creator": id_creator,
    "dating": id_dating,
    "errors": id_errors,
    "feed": id_feed,
    "help": id_help,
    "moderation": id_moderation,
    "navigation": id_navigation,
    "notifications": id_notifications,
    "onboarding": id_onboarding,
    "premium": id_premium,
    "profile": id_profile,
    "search": id_search,
    "settings": id_settings,
    "stories": id_stories,
    "support": id_support,
    "time": id_time,
  },
  "pt": {
    "admin": pt_admin,
    "billing": pt_billing,
    "chat": pt_chat,
    "common": pt_common,
    "creator": pt_creator,
    "dating": pt_dating,
    "errors": pt_errors,
    "feed": pt_feed,
    "help": pt_help,
    "moderation": pt_moderation,
    "navigation": pt_navigation,
    "notifications": pt_notifications,
    "onboarding": pt_onboarding,
    "premium": pt_premium,
    "profile": pt_profile,
    "search": pt_search,
    "settings": pt_settings,
    "stories": pt_stories,
    "support": pt_support,
    "time": pt_time,
  },
  "tr": {
    "admin": tr_admin,
    "billing": tr_billing,
    "chat": tr_chat,
    "common": tr_common,
    "creator": tr_creator,
    "dating": tr_dating,
    "errors": tr_errors,
    "feed": tr_feed,
    "help": tr_help,
    "moderation": tr_moderation,
    "navigation": tr_navigation,
    "notifications": tr_notifications,
    "onboarding": tr_onboarding,
    "premium": tr_premium,
    "profile": tr_profile,
    "search": tr_search,
    "settings": tr_settings,
    "stories": tr_stories,
    "support": tr_support,
    "time": tr_time,
  },
};

/**
 * Get the raw translation resource for a language + namespace, or null.
 */
export function getTranslationResource(
  language: string,
  namespace: string,
): Record<string, unknown> | null {
  const byNamespace = resources[language];
  if (!byNamespace) return null;
  const resource = byNamespace[namespace];
  if (resource === null || resource === undefined) return null;
  return resource as Record<string, unknown>;
}
